# Generated by Django 3.1 on 2020-09-04 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('Feedback', models.CharField(max_length=264)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
