# Generated by Django 3.1 on 2020-09-04 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200904_1458'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Devotee',
        ),
    ]
